### ISSUE TITLE
Node-Red crashes with [error] ReferenceError: OnError is not defined  

### ISSUE THREAD

**Issue by gilmiz** [GoogleCloudPlatform/node-red-contrib-google-cloud#113]
Node-Red crashes when using the PubSub node to publish and subscribe for messages
 
Terminal message is: 

[error] ReferenceError: OnError is not defined  
at Subscription.OnClose (/home/nnn/.node-red/node_modules/node-red-contrib-google-cloud/pubsub-in.js:110:54)
at Subscription.emit (node:events:520:28)
at Subscriber.<anonymous> (/home/nnn/.node-red/node_modules/@google-cloud/pubsub/src/subscription.ts:320:32)
at Subscriber.emit (node:events:520:28)
at ModAckQueue.flush (/home/nnn/.node-red/node_modules/@google-cloud/pubsub/src/message-queues.ts:144:24)  

Testing with a simple flow like
![image](https://user-images.githubusercontent.com/16917848/161501754-f270ab08-10d4-4d54-9830-245c840a6f24.png)
![image](https://user-images.githubusercontent.com/16917848/161503473-ed4d471a-0b38-43d1-83f8-80a382ac28a1.png)

The problem appeared sometime within the last month.

I've tried reinstalling, without any change. 

Did anyone else experience the same? 

/Gilad

**Comment by gylim78** [comment]
Hi there,

I got the same error.
Maybe the same thing happened to you.

I was simulating an internet connection break by turning off the wifi on my laptop and this error appeared about 5 mins after that. This is kind of a problem for me as I am deploying in a Raspberry pi and the internet connection is a mobile connection so I do expect the internet to go down from time to time. 

If anyone has solved this issue or has any suggestions, it would be greatly appreciated.

**Comment by kolban-google** [comment]
Howdy chums ... am on it today!!  Thanks for raising the issue.  Stay tuned.

**Comment by gylim78** [comment]
I was actually looking through the code. 
The issue should be just that the function OnError does not exist. It should be OnClose instead.

I believe that it should be
subscription.removeListener('error', OnClose);

**Comment by kolban-google** [comment]
Ty @gylim78 ... I made the change ... committed to GutHub, published to npm and refreshed at Node-RED

If you could check it out when you can, that would be appreciated.
